name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build -t algn48/node-todo:1 .
          docker ps -a
      - name: login to Docker Hub
        run:   echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "algn48" --password-stdin
      - name: push image to Docker Hub
        run: |
          docker ps -a 
          docker push algn48/node-todo:1
  
