name: Build and Publish Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -t algn48/node-todo:latest .
          docker ps -a
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "algn48" --password-stdin
      - name: Get Latest Tag from Docker Hub and Increment
        id: get_tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/algn48/node-todo/tags/?page_size=1" | jq -r '.results[0].name' | grep -Eo '[0-9]+' || echo 0)
          NEW_TAG=$((LATEST_TAG + 1))
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
      - name: Push Image to Docker Hub
        run: |
          docker ps -a
          docker tag algn48/node-todo:latest algn48/node-todo:${{ env.new_tag }}
          docker push algn48/node-todo:${{ env.new_tag }}

          echo "- **New Incremental Tag:** ${{ env.new_tag }}" >> $GITHUB_STEP_SUMMARY

  generate-summary:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - name: Create Summary for GitHub Actions
        run: |
          echo "## ✅ Docker Image Built and Pushed Successfully" >> $GITHUB_STEP_SUMMARY
          echo "- **Repository:** algn48/node-todo" >> ${{ env.new_tag }}
          echo "- **Latest Tag:** latest" >> $GITHUB_STEP_SUMMARY
          echo "- **New Incremental Tag:** ${{ needs.get-latest-tag.outputs.new_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Docker Hub URL:** [View Image](https://hub.docker.com/r/algn48/node-todo)" >> $GITHUB_STEP_SUMMARY


  update-argocd:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Update Deployment File
        run: |
          sed -i "s|image: algn48/node-todo:.*|image: algn48/node-todo:${{ env.new_tag }}|g" k8s/deployment.yaml
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Updated deployment with new image tag: ${{ needs.get-latest-tag.outputs.new_tag }}"
          git push
