name: Build and Publish Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  # get-latest-tag:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     new_tag: ${{ steps.get_tag.outputs.new_tag }}
  #   steps:
  #     - name: Get Latest Tag from Docker Hub and Increment
  #       id: get_tag
  #       run: |
  #         LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/algn48/node-todo/tags/?page_size=1" | jq -r '.results[0].name' | grep -Eo '[0-9]+' || echo 0)
  #         NEW_TAG=$((LATEST_TAG + 1))
  #         echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
  #         echo "new_tag=$NEW_TAG" 
  #         echo  $GITHUB_OUTPUT

  build-image:
    runs-on: ubuntu-latest
    # needs: get-latest-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t algn48/node-todo:latest -t algn48/node-todo:${{ needs.get-latest-tag.outputs.new_tag }} .

  push-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "algn48" --password-stdin
      - name: Get Latest Tag from Docker Hub and Increment
        id: get_tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/algn48/node-todo/tags/?page_size=1" | jq -r '.results[0].name' | grep -Eo '[0-9]+' || echo 0)
          NEW_TAG=$((LATEST_TAG + 1))
      - name: Push Image to Docker Hub
        run: |
          docker push algn48/node-todo:$NEW_TAG

  generate-summary:
    runs-on: ubuntu-latest
    needs: push-image
    steps:
      - name: Create Summary for GitHub Actions
        run: |
          echo "## ✅ Docker Image Built and Pushed Successfully" >> $GITHUB_STEP_SUMMARY
          echo "- **Repository:** algn48/node-todo" >> $GITHUB_STEP_SUMMARY
          echo "- **Latest Tag:** latest" >> $GITHUB_STEP_SUMMARY
          echo "- **New Incremental Tag:** ${{ needs.get-latest-tag.outputs.new_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Docker Hub URL:** [View Image](https://hub.docker.com/r/algn48/node-todo)" >> $GITHUB_STEP_SUMMARY
